package it.pagopa.infrastructure.fuzzing;

public enum FuzzScenario {
    REPLACED_WITH_NULL,
    REMOVED,
    REPLACED_WITH_EMPTY_STRING,
    REPLACED_WITH_BLANK_STRING,
    REPLACED_WITH_LONG_STRING,
    REPLACED_WITH_SQL_INJECTION,
    REPLACED_WITH_XSS,
    REPLACED_WITH_WRONG_TYPE_STRING,
    REPLACED_WITH_WRONG_TYPE_NUMBER,
    REPLACED_WITH_WRONG_TYPE_DECIMAL,
    REPLACED_WITH_ZERO,
    REPLACED_WITH_NEGATIVE_VALUE,
    REPLACED_WITH_MIN_VALUE,
    REPLACED_WITH_MAX_VALUE,
    REPLACED_WITH_MALFORMED_UUID,
    REPLACED_WITH_NIL_UUID,
    REPLACED_WITH_UNKNOWN_ENUM
}
