# ============================================================================
# Test Profile Configuration
# ============================================================================

# ============================================================================
# External Configuration Import
# ============================================================================
spring:
  config:
    activate:
      on-profile: qa

# ============================================================================
# URLs Configuration
# Base URLs and routes for test environment
# ============================================================================
interop:
  auth:
    aws:
      region: eu-south-1
    bearer:
      well-known-url: https://qa.interop.pagopa.it/.well-known/jwks.json
      issuer: qa.interop.pagopa.it
      audience: qa.interop.pagopa.it/ui
      duration-sec: 14400
    oauth:
      server: https://auth.qa.interop.pagopa.it/token.oauth2
    client-assertion:
      audience: auth.qa.interop.pagopa.it/client-assertion
      grant_type: client_credentials
      assertion_type: urn:ietf:params:oauth:client-assertion-type:jwt-bearer
  api:
    base-url:
      bff: https://selfcare.qa.interop.pagopa.it/1.0/backend-for-frontend
  web:
    base-url: https://selfcare.qa.interop.pagopa.it/ui/it
    catalog: ${interop.web.base-url}/catalogo-e-service
    provision-catalog: ${interop.web.base-url}/erogazione/e-service     #catalogo pagina erogazione