# ============================================================================
# Test Profile Configuration
# ============================================================================

# ============================================================================
# External Configuration Import
# ============================================================================
spring:
  config:
    activate:
      on-profile: dev

# ============================================================================
# URLs Configuration
# Base URLs and routes for test environment
# ============================================================================
interop:
  auth:
    aws:
      region: eu-south-1
    bearer:
      well-known-url: https://dev.interop.pagopa.it/.well-known/jwks.json
      issuer: dev.interop.pagopa.it
      audience: dev.interop.pagopa.it/ui
      duration-sec: 14400
    oauth:
      server: https://auth.dev.interop.pagopa.it/token.oauth2
    client-assertion:
      audience: auth.dev.interop.pagopa.it/client-assertion
      grant_type: client_credentials
      assertion_type: urn:ietf:params:oauth:client-assertion-type:jwt-bearer
  api:
    base-url:
      bff: https://selfcare.dev.interop.pagopa.it/1.0/backend-for-frontend
  web:
    base-url: https://selfcare.dev.interop.pagopa.it/ui/it