# ============================================================================
# Test Profile Configuration
# ============================================================================

# ============================================================================
# External Configuration Import
# ============================================================================
spring:
  config:
    activate:
      on-profile: dev

# ============================================================================
# URLs Configuration
# Base URLs and routes for test environment
# ============================================================================
interop:
  auth:
    aws:
      region: eu-south-1
    bearer:
      well-known-url: https://dev.interop.pagopa.it/.well-known/jwks.json
      issuer: dev.interop.pagopa.it
      audience: dev.interop.pagopa.it/ui
      duration-sec: 14400
    oauth:
      server:
        base-url: https://auth.dev.interop.pagopa.it
        sync: ${interop.auth.oauth.server.base-url}/token.oauth2
        async: ${interop.auth.oauth.server.base-url}/token.oauth2.async
    client-assertion:
      audience: auth.dev.interop.pagopa.it/client-assertion
      grant_type: client_credentials
      assertion_type: urn:ietf:params:oauth:client-assertion-type:jwt-bearer
  api:
    base-url:
      bff: https://selfcare.dev.interop.pagopa.it/0.0/backend-for-frontend
      m2m:
        v3: https://api.dev.interop.pagopa.it/v3
  web:
    base-url: https://selfcare.dev.interop.pagopa.it/ui/it
    catalog: ${interop.web.base-url}/catalogo-e-service