cucumber.execution.parallel.enabled=true
cucumber.execution.parallel.config.strategy=dynamic

# Test di contratto: Default locale / IntelliJ: debugging leggibile
junit.jupiter.execution.parallel.enabled=false
junit.jupiter.execution.parallel.mode.default=same_thread

# Output JUnit
junit.platform.output.capture.stdout=false
junit.platform.output.capture.stderr=false
