cucumber.execution.parallel.enabled=true
cucumber.execution.parallel.config.strategy=dynamic

# Usa la strategia fixed per ammortizzare le istanze del Browser in parallelo
#cucumber.execution.parallel.config.strategy=fixed
#cucumber.execution.parallel.config.fixed.parallelism=4

# Test di contratto
junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.mode.default=concurrent
junit.jupiter.execution.parallel.config.strategy=dynamic
