<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.3</version>
        <relativePath/>
    </parent>

    <groupId>it.pagopa</groupId>
    <artifactId>interop-suite</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>interop-suite</name>

    <properties>
        <java.version>17</java.version>
        <cucumber.version>7.14.0</cucumber.version>
        <jjwt.version>0.12.6</jjwt.version>
        <spring-plugin.version>4.1.0</spring-plugin.version>
        <rest-assured.version>5.5.0</rest-assured.version>
        <swagger-request-validator.version>2.46.1</swagger-request-validator.version>
        <bff.openapi.url>https://raw.githubusercontent.com/pagopa/interop-be-monorepo/refs/heads/develop/packages/api-clients/open-api/bffApi.yml</bff.openapi.url>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>2.25.53</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <!-- ========================= -->
    <!-- TODO: DA ELIMINARE, SEZIONE UTILE DURANTE IL REFACTOR PER EVITARE ERRORI DI COMPILAZIONE SUL PREGRESSO -->
    <!-- ========================= -->
    <profiles>
        <profile>
            <id>refactor</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <configuration>
                            <excludes>
                                <exclude>it/pagopa/interop/bff/**</exclude>
                                <exclude>it/pagopa/interop/common/**</exclude>
                                <exclude>it/pagopa/interop/web/**</exclude>
                            </excludes>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <dependencies>

        <!-- ========================= -->
        <!-- FE FRAMEWORK -->
        <!-- ========================= -->

        <dependency>
            <groupId>it.frontend.e2e.framework</groupId>
            <artifactId>web-core</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>it.frontend.e2e.framework</groupId>
            <artifactId>annotations</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <!-- ========================= -->
        <!-- CUCUMBER -->
        <!-- ========================= -->

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-spring</artifactId>
            <version>${cucumber.version}</version>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit-platform-engine</artifactId>
            <version>${cucumber.version}</version>
        </dependency>

        <!-- ========================= -->
        <!-- SPRING BOOT -->
        <!-- ========================= -->

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <!-- ========================= -->
        <!-- SPRING PLUGIN -->
        <!-- ========================= -->

        <dependency>
            <groupId>org.springframework.plugin</groupId>
            <artifactId>spring-plugin-core</artifactId>
            <version>${spring-plugin.version}</version>
        </dependency>

        <!-- ========================= -->
        <!-- JUNIT PLATFORM SUITE API (@Suite) -->
        <!-- ========================= -->

        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-suite-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-suite-engine</artifactId>
        </dependency>

        <!-- ========================= -->
        <!-- INSTANCIO -->
        <!-- ========================= -->

        <dependency>
            <groupId>org.instancio</groupId>
            <artifactId>instancio-junit</artifactId>
            <version>5.6.0</version>
        </dependency>

        <!-- ========================= -->
        <!-- Lombok -->
        <!-- ========================= -->

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- ========================= -->
        <!-- JWT -->
        <!-- ========================= -->

        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-api</artifactId>
            <version>${jjwt.version}</version>
        </dependency>

        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-impl</artifactId>
            <version>${jjwt.version}</version>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-jackson</artifactId>
            <version>${jjwt.version}</version>
            <scope>runtime</scope>
        </dependency>

        <!-- ========================= -->
        <!-- Client Generation dependencies -->
        <!-- ========================= -->

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>${rest-assured.version}</version>
        </dependency>

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-path</artifactId>
            <version>${rest-assured.version}</version>
        </dependency>

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>xml-path</artifactId>
            <version>${rest-assured.version}</version>
        </dependency>

        <dependency>
            <groupId>com.atlassian.oai</groupId>
            <artifactId>swagger-request-validator-core</artifactId>
            <version>${swagger-request-validator.version}</version>
        </dependency>

        <dependency>
            <groupId>com.atlassian.oai</groupId>
            <artifactId>swagger-request-validator-restassured</artifactId>
            <version>${swagger-request-validator.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>

        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>1.3.2</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
            <version>3.0.2</version>
        </dependency>

        <!-- ========================= -->
        <!-- Map Struct -->
        <!-- ========================= -->

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>1.6.3</version>
        </dependency>

        <!-- ========================= -->
        <!-- AWS KMS: Interop Bearer Auth Dependency -->
        <!-- ========================= -->

        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>kms</artifactId>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>

        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.1</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                    <useModulePath>false</useModulePath>

                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.42</version>
                        </path>

                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </path>

                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>1.6.3</version>
                        </path>

                        <path>
                            <groupId>it.frontend.e2e.framework</groupId>
                            <artifactId>processor</artifactId>
                            <version>1.0-SNAPSHOT</version>
                        </path>

                        <path>
                            <groupId>it.frontend.e2e.framework</groupId>
                            <artifactId>web-core</artifactId>
                            <version>1.0-SNAPSHOT</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>

                <executions>
                    <execution>
                        <id>default-testCompile</id>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <useModulePath>false</useModulePath>
                    <testClassesDirectory>${project.build.outputDirectory}</testClassesDirectory>
                    <includes>
                        <include>**/suite/**</include>
                    </includes>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.19.0</version>
                <executions>
                    <!-- Bff API -->
                    <execution>
                        <id>generate-bff-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>process-resources</phase>
                        <configuration>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=java.lang.String</typeMapping>
                            </typeMappings>
                            <inputSpec>${bff.openapi.url}</inputSpec>
                            <generatorName>java</generatorName>
                            <library>rest-assured</library>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <skipValidateSpec>true</skipValidateSpec>
                            <configOptions>
                                <apiPackage>it.pagopa.interop.generated.openapi.clients.bff.api</apiPackage>
                                <modelPackage>it.pagopa.interop.generated.openapi.clients.bff.model</modelPackage>
                                <dateLibrary>java8</dateLibrary>
                                <annotationLibrary>none</annotationLibrary>
                                <documentationProvider>source</documentationProvider>
                                <openApiNullable>false</openApiNullable>
                                <useAbstractionForFiles>true</useAbstractionForFiles>
                                <useBeanValidation>false</useBeanValidation>
                                <serializableModel>true</serializableModel>
                                <serializationLibrary>jackson</serializationLibrary>
                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                                </additionalModelTypeAnnotations>
                            </configOptions>
                            <apiPackage>it.pagopa.interop.generated.openapi.clients.bff.api</apiPackage>
                            <modelPackage>it.pagopa.interop.generated.openapi.clients.bff.model</modelPackage>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

</project>